Automattic/vip-cli

bin/vip-configure.js
bin/vip.js

We can use the version set in package.json to set the version in the
CLI. We also shouldn't need the version in sub-commands as that's
inherited from the main CLI.

Imply the version from the package itself!

---

bin/vip-import.js
bin/vip.js
package.json
src/utils.js

Adds two new commands:
```
$ vip import sql --help
Usage: sql [options] <site> <file>
Import SQL to a VIP Go site
Options:
-h, --help  output usage information
```
```
$ vip import files --help
Usage: files [options] <site> <directory>
Import files to a VIP Go site
Options:
-h, --help                output usage information
-t, --types <types>       Types of files to import
-p, --parallel <threads>  Number of parallel uploads
-i, --intermediate        Upload intermediate images
-f, --fast                Skip existing file check
```

Add imports

---

src/src/utils.js

The site parameter should be an exact match, which we can do with the
new domain_name query parameter on site queries.

Switch to domain_name query for findSite

---

src/bin/vip.js
src/src/utils.js

Runs a given command on a local container for the site specified.
If a container doesn't exist, output an error.
TODO:
Fixes #28

Add helper command to run CLI commands on containers

---

src/bin/vip-import.js

Setting the content length disables the default chunked encoding. Trying to upload a file that is too large causes the files api to prematurely hang up. Fixes #38

Use chunked encoding for uploading files

---

src/bin/vip-import.js
src/src/import.js

When a single directory has tons of images, we have to avoid putting
every file in the queue at the same time. In the extreme case, a site
could have all files in the same directory, which results in a list of
all files being stored in RAM.
This addresses that by only putting 5k files at a time in the queue to
process. If there are more than that, we add the first 5k files and a
placeholder to be processed after that. When we get to the placeholder,
we read the directory list again and add the next 5k files until all
files have been processed. This adds approximately N/5000 more disk
operations, but can significantly reduce RAM usage.
The 5000 limit was just a guess. We can adjust that if necessary.
Note: While this effectively addresses the problem of a few directories
with lots (> 50k) …

Files importer: lower memory usage for huge directories

---

src/bin/vip-api.js
src/bin/vip-cli.js
src/bin/vip-db.js
src/bin/vip-deploy.js
src/bin/vip-import.js
src/bin/vip-login.js
src/bin/vip.js

* All sub-commands get their own executable -- keeps vip.js easier to read and maintain
* Use const for all module requires
* Include as much usage information as possible in command definitions
Also: Deprecate --export for `vip db`. You can still use export and
shouldn't notice a difference unless you're trying to see the full
database in your terminal (probably not that useful). Instead, we detect
when stdout is piped and assume you want a mysqldump.

Cleanup Round 2

---

src/bin/vip-cli.js
src/bin/vip-sandbox.js
src/lib/sandbox.js

When you exit a sandbox container, we stop it. The next time you run
a command, we automatically start the stopped container instead of
creating a new one. In the future we can clean up stopped containers
after some time.
Fixes #52 
Depends on #54

Stop unused containers

---

src/bin/vip-import.js
src/lib/db.js

Stream the import through gunzip or unzip, depending on the file type.
There may be more reliable ways to determine the compression method.
NOTE: Makes the import progress completely wrong. Not really sure how we
can get an accurate file size without reading the whole file into memory
first, which seems like a waste of time. The data still seems useful
and is accurate for uncompressed files, so I think we should leave it
in place.
Fixes #40

Add support for importing .zip and .gz mysql dumps

---

src/bin/vip.js

For now we remove `vip stacks` and `vip sandbox` if you're not on a *.vipv2.net sandbox.
Fixes #59

Only include commands that require a sandbox if you're on a sandbox.

---

src/lib/sandbox.js

Watch for ENOENT and continue with sandbox start when the file doesn't exist.
Fixes #95

Fix sandbox start when sbox file doesn't exist

---

package.json

Makes development easier/faster to not have to run `npm install` (or the full babel command) all the time.

Separate build script from pre-install

---

src/bin/vip-db.js
src/lib/sandbox.js
src/lib/utils.js

Especially, when we run `sandbox start`, it's not always obvious we've been switched into the sandbox shell. This displays a notice that hopefully helps make that a bit clearer.
```
$ node build/bin/vip.js sandbox start example.com
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Logging in to sandbox container:
example-com-vipco_web_dev_0001
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
```

Show info about command we're running on sandbox

---

src/bin/vip-import.js
src/lib/utils.js

Uses the displayNotice util.
```
$ ./build/bin/vip import files example.com uploads/
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Importing files for site:
-- Site: example.com (#123)
-- Environment: production
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Are you sure?
$ ./build/bin/vip.js import sql example.com sql.sql
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Importing SQL for site:
-- Site: example.com (#123)
-- Environment: production
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Are you sure?
```

Standardize alerts for import commands

---

src/bin/vip-import.js

Make the extension check case-insensitive

---

package.json
src/bin/vip-site.js
src/bin/vip.js
src/lib/host.js
src/lib/site.js

Triggers an `upgrade_wp` action for the given site and provides progress on container state throughout.
```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Triggering web server update/rebuild:
-- Site: example.com (#309)
-- Environment: production
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Successfully created wp upgrade host action for site 123 (action #123456)
#10006 - example-comgo-vipco_web_0004 - running
#10007 - example-comgo-vipco_web_0005 - running
Action #123456: queued
Update complate 🎉🎉🎉
```
We wait for the `core update-db` host action to complete as the signal that we're done. The `Container Status` and `wp-cli Status` sections update throughout the process.

Add `site update` command

---

src/bin/vip-stacks.js

Instead of repeatedly printing the same thing on a new line, we
can use single-line-log to update a single line.

Use single-line-log on `vip stacks update` output.

---

src/lib/config.js

If a config file has invalid data, we end up failing spectacularly. Better handle those cases by watching for SyntaxErrors.
Fixes #122

Handle invalid config in config files

---

src/bin/vip-import.js

Throw and error and bail if it doesn't.
```
build/bin/vip.js import db ellaminnowpea.xyz file.js
Failed to get import file (file.js) due to the following error:
ENOENT: no such file or directory, lstat 'file.js'
```
Fixes #137

Check if import file exists

---

src/bin/vip-files.js

Don't prematurely close the destination file. Since we're piping the
http stream to the writeStream, the file should automatically be closed.
Fixes #140

Fix incomplete file downloads

---

src/bin/vip-site.js

Slowly chipping away at the reasons I need to switch over to the admin console.
I somewhat often have to load the admin console to search for a site -- maybe to find the exact spelling of a site name or to get the site ID for searching through logs.
This is pretty basic for now. It just include the ID, Name, and Primary Domain Name of first 10 search results. Over time we can add filters and optionally output more fields. Would also be nice to standardize formatting across the various `list` commands per https://github.com/Automattic/vip-cli/issues/117

Add basic site search command

---

src/bin/vip-site.js
src/lib/site.js

Named `vip site upgrade` for now to avoid collision with existing site
update command. For now it just starts upgrades and lists the sites.
Eventually we need to list the related host actions in the API so that
we can easily poll them. We can also optionally take a site ID and use
the same command for single-site upgrades as well as bulk upgrades.

wp bulk upgrade initial commit

---

src/lib/sandbox.js
src/lib/utils.js

Instead of a message that transitioning containers cannot be actioned
on, we can poll the container state and take action when they're ready.

Wait for transitioning containers

---

src/bin/vip-sandbox.js
src/lib/sandbox.js

So we don't have to pass `--allow--root` to every wp-cli command.
Historically it's intentionally impossible to define allow-root in
a config file (https://github.com/wp-cli/wp-cli/issues/1838). Maybe
needs to be reconsidered in Docker containers, but for now let's run
as `nobody` by default.

vip sandbox: Run as `nobody`

---

src/bin/vip-import.js
src/lib/files.js
src/lib/site.js

Normally the importer sends a HEAD request for each file and skips it if
it already exists. This is designed to make imports faster by not
transfering lots of unnecessary data. If we know none of the files
exist, it's faster to skip the 404 checks though. There's an option for
this built into the importer now `--fast`, but it doesn't really get
used.
This detects "new" sites (currently defined by less than 100 images
uploaded) and skips the 404 checks automatically.

Importer: Always use 'fast' mode for new sites.

---

src/bin/vip-sandbox.js
src/lib/sandbox.js

This finishes transitioning sandbox stop logic to the
/sandboxes/:id/stop endpoint. This is needed because the /container/stop
endpoint isn't granular enough to give start/stop access to a specific
set of containers (i.e. on your sandbox host). It is important because
it means we're now stopping all containers on your sandbox host for a
given site when you run `vip sandbox stop`. In practice, this is unlikely
to change anything unless you were creating multiple running sandbox containers
at once.
This PR also removes the maybePrompt helper function, which we were
using to decide which sandbox container to take action on if you had
multiple. We were only using it in the `vip sandbox pause` subcommand
anymore, which is also being removed becuase there is no
`/sandboxes/:id/pause` endpoint …

Fix sandbox stop

---

src/bin/vip-sandbox.js

Removes the `--root` flag of `vip sandbox start` and always starts as
`root`, but `vip sandbox run` always starts as `nobody`. Since `sandbox
run` doesn't open an interactive shell, it doesn't really make sense to
use it for write operations inside the container. It's mostly used for
running wp-cli commands.

Sandbox: vip sandbox always starts as root

---

src/bin/vip-files.js

We were missing the last page of exports because of importing "page 0"
first.

vip files: Fix off-by-1 error

---

src/lib/db.js

To avoid placing a large blocking LOCK on tables when generating the export.
https://dev.mysql.com/doc/refman/5.7/en/mysqldump.html#option_mysqldump_single-transaction
https://dev.mysql.com/doc/refman/5.7/en/mysqldump.html#option_mysqldump_quick

Make db export use single-transaction and quick

---

src/bin/vip-import.js
src/lib/utils.js

For DB imports. If we need to loop through and import a batch of files, it's helpful to explictly skip the confirmation step, if needed.

Add ability to skip confirmation step

---

src/bin/vip-site.js

We don't care about stopped/uninitialized containers during upgrades.
(At least not for the purposes of the bulk upgrade; we may want to
delete any stopped containers that can't be upgraded in the API.)
We need to ignore these so as to not get the upgrader stuck.
Fixes #176

Bulk Upgrades: Don't hang on stopped/uninitialized containers

---

package.json

For continuous building while developing.
```
$ npm run build:watch
> wpvip-cli@0.14.0-dev build:watch /home/vipdev/cli
> babel src --out-dir=build --watch
src/bin/vip-api.js -> build/bin/vip-api.js
src/bin/vip-db.js -> build/bin/vip-db.js
...
```
Fixes #127

Add 'build:watch' script

---

src/lib/db.js

http://sql-info.de/mysql/notes/I-am-a-dummy.html
```
mysql> update wp_posts set post_content = 'test';
ERROR 1175 (HY000): You are using safe update mode and you tried to update a table without a WHERE that uses a KEY column
```

Add safe-updates

---

src/bin/vip-import.js

findAndConfirmSite passes an error to the callback since #191 -- we need to account for that.

Fix file import

---

src/bin/vip-import.js

Even if WordPress allows gz, zip, tar, etc. we probably don't want to blindly import these. The importer will put them in a report and if it turns out that we do need to import them, we can always add them in `--extra-types`

Don't import file archives by default

---

src/bin/vip-sandbox.js

Removes non-functional `--all` option from `vip sandbox delete`. To delete all containers, you can use `vip sandbox purge`.
Fixes #215

Fix `vip sandbox delete` docs

---

src/bin/vip-files.js
src/constants.js

The files service IP is upload-only. To read files, we must use the
anycast IP address. We're hard-coding it here in case the domain name
in question doesn't point to VIP Go.

Download files from the anycast IP address

---

src/bin/vip-db.js

Howdy!
As per #234, it would be nice if folks could get the configured InnoDB buffer pool size with the command `vip db buffer-pool <site>`.  This PR does just that by pulling the data from both the global SQL variable and the metadata container via API for it.  We do both methods because if there ever was a difference in values, we would see it side-by-side.
Sample output:
```
-- Site: 334
-- Domain: vccircle-com-develop.go-vip.co
-- Environment: develop
-- Growth Factor: 0.75
-- Configured InnoDB (mb): 128
+---------+----------+----------+-----------+---------------+
| data_mb | index_mb | total_mb | innodb_mb | configured_mb |
+---------+----------+----------+-----------+---------------+
|     515 |      163 |      677 |       508 |           128 | …
```

Add configured innodb buffer pool size to `vip db buffer-pool`

---

src/lib/db.js

It's safer to export the database from a slave (assuming no lag) than
adding load to a master db and potentially blocking writes.
Related to #169

Export database via db slave

---

src/bin/vip-import.js

There are some assumptions that the upload path will contain `/uploads`,
so we need to return an error if it doesn't.

Importer: Source must contain `/uploads`

---

src/bin/vip-import.js
src/lib/import.js

We don't need access to the importer options anywhere else in the class, so let's limit the scope.

Importer: Limits options scope

---

src/lib/sandbox.js

When a sandbox is created, the state doesn't immediately switch to
running. We should consider all active containers that aren't stopped to
be running for this purpose.

Fix running sandbox limit race condition

---

src/bin/vip-sandbox.js

Here's what it looks like:
``` bash
$ vip sandbox run --help
Usage: run [options] <site> <command...>
Run a wp-cli command on a sandbox container. Use a double dash (--) before the WP CLI command, example:
vip sandbox run exhibit.go-vip.co -- wp user list --field=ID
Options:
-h, --help      output usage information
--skip-confirm  Run the command without asking for confirmation
```

Add an example to encourage use of double dashes for run commands

---

src/bin/vip-db.js
src/lib/utils.js

To make it easier to recognize production sites in command prompts,
we'll show them in red and add emphasis (bold and caps).

Colorize environment names in command prompts

---

src/bin/vip-import.js

This switches the `wp cache flush` that runs after database imports to `wp vip migration cleanup`, which flushes the cache after some other cleanup.
https://github.com/Automattic/vip-go-mu-plugins/pull/786

Run vip migration cleanup after import

---

src/bin/vip-import.js

Don't allow file imports to non-production environments by default
because UnionFS makes them available to all child environments
automatically.
Fixes #146

Block files imports to non-production environments

---

src/lib/import.js

We need `uploads` to be in the file path, but it doesn't necessarily have to be the first thing in the path. There can be some prefix and we'll still upload it to the correct place.
Fixes #279

Don't require uploads at the start of the path

---

src/lib/utils.js

Otherwise we never find out if the request fails for some reason.

When refreshing credentials, check for error

---

package.json

We need to rename the binary because the new, public CLI will be `vip`.

Rename the binary to goop

---

src/bin/vip-db.js

When we're setting the innodb buffer pool size, it doesn't always need
to be bigger than the database. It just needs to be bigger than the
working set. We'll guess the working set on average is around 50% of the
data + the indexes. We can adjust this if necessary.
Fixes #285

Add acceptable_mb to buffer-pool estimate

---

scripts/postuninstall

The postinstall script was doing the opposite of what we wanted
(deleting the config if we said no).
Fixes #303

Fix postinstall prompt

---

src/lib/sandbox.js

If the sandbox file doesn't exist, create one. It's likely that
something has gone wrong if we get here, but we can't really recover
from that unfortunately.
Also fixes #303

Properly handle missing sandbox file during decrement
