Automattic/vip-cli

bin/vip-api.js
bin/vip.js

* `vip api GET <endpoint>`
* `vip api POST [--data=<data>] <endpoint>`
* `vip api PUT [--data=<data>] <endpoint>`
* `vip api DELETE <endpoint>`

Add vip api subcommand.

---

src/bin/vip.js
src/src/utils.js

Only show internal commands to a12s.

---

package.json
src/bin/vip-import.js
src/bin/vip.js
src/src/db.js

Stream db import

---

package.json
src/src/db.js

Add progress bar to DB importer

---

src/bin/vip.js
src/src/utils.js

Add logout command

---

package.json
src/src/db.js

Throttle sql imports to 1mpbs

---

src/bin/vip-import.js

We use the same priorityQueue (DFS) to count all the files, taking
into account file types, and whether or not they are resized. Then we
set up the progress bar and run the queue again, actually uploading
files this time.
fixes #14

Fix file counting

---

src/bin/vip.js
src/src/utils.js

Return error for unregistered sub-commands.

---

src/bin/vip-import.js
src/src/import.js

Move to async disk IO to speed up the importer and avoid call stack
overflows.
Fixes #36

Fix: Importing large number of files

---

package.json
src/bin/vip-cli.js
src/bin/vip-sandbox.js
src/bin/vip.js
src/lib/sandbox.js

Makes it easy to start/stop/pause/delete existing sandboxes.

Add vip sandbox command

---

src/bin/vip-stacks.js
src/bin/vip.js

Triggers a software update for the current host and polls the
host actions endpoint until it's done.
Fixes #51

Add vip stack update

---

src/bin/vip-sandbox.js
src/lib/sandbox.js

Use sandbox container endpoints to deal with ACL issues.

Fix sandbox container endpoints

---

package.json
src/lib/sandbox.js

Color-code sandbox state

---

src/bin/vip-import.js
src/lib/db.js

Sets the limit on database imports in MB/s.

Add --throttle to specify `vip import database` limit

---

src/bin/vip-sandbox.js

We previously gave the illusion that you could stop one container at a
time. Due to the way sandbox containers are identified, you must stop
them all at once.
Fixes #67

Fix `vip sandbox stop` ui.

---

src/lib/api.js

Adds middleware to superagent functions which intercepts 401
response codes and bails with an error message.
Later we can automatically run vip login as well.
Fixes #79

Detect invalid/expired tokens and ask to login again.

---

src/lib/utils.js

Parse URL passed as site param

---

src/bin/vip-files.js
src/bin/vip.js
src/lib/utils.js

Add `vip files` command to run exports

---

package.json
src/bin/vip.js

Fixes #46, props @mjangda for the package recommendation.

Add update notifications via update-notifier

---

package.json
scripts/postuninstall

That removes the `vip-cli` config directory

Add uninstall script

---

src/bin/vip-stacks.js

Triggers `software_update` to deploy updated mu-plugins across all hosts.

Add `vip stacks deploy`

---

src/lib/sandbox.js
src/lib/utils.js

With a bonus sweet loading indicator!

Use single-line-log when waiting for sandbox

---

src/bin/vip-import.js

Add all WP default file types to uploader

---

.travis.yml
package.json
src/bin/vip-api.js
src/bin/vip-db.js
src/bin/vip-deploy.js
src/bin/vip-files.js
src/bin/vip-import.js
src/bin/vip-login.js
src/bin/vip-sandbox.js
src/bin/vip-site.js
src/bin/vip-stacks.js
src/bin/vip.js
src/lib/api.js
src/lib/config.js
src/lib/db.js
src/lib/host.js
src/lib/import.js
src/lib/sandbox.js
src/lib/site.js
src/lib/utils.js

Adds eslint config and CI (Travis) config.
Also includes eslint fixes, most from `eslint --fix` (mostly spacing).
Fixes #124

Add eslint and ci

---

src/lib/utils.js

Send single-line-log output to stdout

---

package.json

Tab completions fail fairly often, but its' relatively inconsequential.
Fixes #136

Slightly better tabtab error.

---

src/bin/vip-sandbox.js
src/lib/sandbox.js

Abstract sbox file inc and dec operations

---

src/bin/vip-import.js

Add log of skipped files

---

src/bin/vip-sandbox.js
src/lib/sandbox.js
src/lib/utils.js

See #77 
```
$ vip sandbox run 59 -- wp user list --field=ID 
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Running command on container:
-- Command: wp user list --field=ID
-- Container: v2joshbetzcom_web_dev_0031
-- Site: v2.joshbetz.com (#59)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Are you sure? y
3
2
4
```

Add vip sandbox run

---

src/bin/vip-site.js
src/bin/vip-stacks.js
src/lib/sandbox.js
src/lib/utils.js

This way we can redirect output from vip sandbox run without
getting a bunch of unnecessary sandbox output included in stdout.

Log output notices and prompts to stderr

---

src/bin/vip-deploy.js

Deploy via domain

---

src/bin/vip-sandbox.js
src/lib/sandbox.js

Provides the ability to delete all stopped sandbox containers.
```
$ vip.js sandbox purge
This will delete all 1 sandbox containers on your host. Are you sure? y
Deleting container abcd-xyzgo-vipco_web_dev_0010 (#12345)
All done.
```

Add `sandbox purge` command

---

src/bin/vip-files.js
src/bin/vip-import.js

Related: https://github.com/Automattic/vip-go-api/pull/922

Set pagesize: 0 where we only care about totalrecs

---

src/bin/vip-host-action.js
src/bin/vip.js
src/lib/host.js

```
vip host-action create <action> --host <host> [--payload <payload>]
vip host-action requeue <host> <host-action>
vip host-action list --host <host> [--status <status>] [--watch]
```

Add host action command

---

src/bin/vip-import.js
src/lib/import.js

Fixes #106 
Fixes #185 
Fixes #177 
Fixes #158 
Also fixes duplicate filenames in the output log.

Fix importing invalid filenames

---

src/bin/vip-sandbox.js

Pass --help to `vip sandbox run`

---

src/bin/vip-site.js

Bulk Upgrades: Only show error message if there are errors

---

src/bin/vip-site.js

We can use the same upgrade command regardless of whether we want to
upgrade a single site or a group of sites.

Remove `vip site update <site>` in favor of `vip site upgrade --site <site>`

---

src/bin/vip-site.js

Color-code container status during upgrades

---

src/bin/vip-import.js

Skip big files

---

src/bin/vip-site.js

Don't hang bulk upgrades on stopped containers

---

scripts/postuninstall

Deleting credentials on postinstall has the unintended side effect of deleting on upgrade.

Don't delete credentials on postinstall

---

src/bin/vip-db.js
src/lib/utils.js

Add example/acceptable responses to 'Are You Sure?' type prompts.
Fixes #217

Append (y/n) to promptly.confirm

---

src/bin/vip-db.js
src/lib/db.js

https://dba.stackexchange.com/a/27341
Fixes #180

Add buffer-pool command to calculate ribps

---

src/bin/vip.js
src/lib/api.js
src/lib/utils.js

Use the new currentUserCan functions to decide which commands to display
to the current user.
Depends on some API changes.
Fixes #224

Add currentUserCan support

---

src/bin/vip-token.js
src/bin/vip.js

* vip token list: List current user's tokens.
* vip token create: Create a token for a given user with a given expiry.

Add `vip token` command

---

src/bin/vip-files.js
src/bin/vip-import.js
src/constants.js
src/lib/import.js

Update files service endpoint

---

package.json
src/lib/api.js

You can define a proxy via an environment variable, PROXY.
For example:
PROXY=socks://127.0.0.1:8080 vip <command>
See https://github.com/Automattic/vip-js-sdk/pull/12

Add proxy support

---

src/bin/vip-db.js

db: Check err exists before reading properties

---

src/bin/vip-import.js

Importer: Catch upload errors

---

src/lib/import.js

queue.idle() = queue length + worker length = 0, which is exactly what we want to measure here.

Importer: Simplify .drain() logic

---

src/lib/db.js

Instead of the switch that uses separate endpoints based on slave or master db.

Use single `/db` endpoint to look for connection

---

src/lib/db.js

I'm getting an error on sites that shouldn't error:
```
Error: Could not find a suitable database connection
```
Reverts Automattic/vip-cli#252

Revert "Use single `/db` endpoint to look for connection"

---

src/lib/db.js

Add validation for SQL imports

---

src/lib/db.js

Validate SQL files before starting import

---

src/bin/vip-site.js

List CLI containers in upgrade command

---

package.json
scripts/postuninstall
src/bin/vip.js

This was never configured correctly and seems to only cause problems.
Let's remove it for now and we can potentially add it back later.

Remove tabtab

---

src/bin/vip-import.js

**Note:** Merge after 1/1/2018

Allow search-replace to production sites

---

src/bin/vip-import.js
src/lib/import.js

Log import errors

---

src/lib/utils.js

We'll automatically refresh the cached list of caps hourly.
Fixes #228

Update user caps hourly

---

package.json

Prepublish is deprecated.
Fixes #281

Switch to `npm run prepare` from `npm run prepublish`

---

src/bin/vip-site.js

A bit confusing in the context of upgrades since it's not the full count of running containers but upgraded containers.

Change "Running" label => "Done"

---

src/lib/utils.js

There's a bad race condition in the credential refreshing code
that causes repeated logouts. I was able to reproduce by moving
the setCredentials code outside the conditional and it only works
about 50% of the time :( Reverting for now.

Remove credential refreshing

---

package.json

Alias viggo vipgo goop

---

README.md

Changed in examples and in references to the command

Change command title and name
